// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "button": {
      name: "button",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/button.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/button.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dialog": {
      name: "dialog",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/dialog.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/dialog.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "input": {
      name: "input",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/input.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/input.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "kbd": {
      name: "kbd",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/kbd.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/kbd.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "number-input": {
      name: "number-input",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/number-input.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/number-input.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dropdown-menu": {
      name: "dropdown-menu",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/dropdown-menu.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/dropdown-menu.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "accordion": {
      name: "accordion",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/accordion.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/accordion.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "checkbox": {
      name: "checkbox",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/checkbox.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/checkbox.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "tabs": {
      name: "tabs",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/tabs.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/tabs.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "avatar": {
      name: "avatar",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/avatar.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/avatar.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "tooltip": {
      name: "tooltip",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/tooltip.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/tooltip.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "select": {
      name: "select",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/select.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/select.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toggle": {
      name: "toggle",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/toggle.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/toggle.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "popover": {
      name: "popover",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/popover.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/popover.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "separator": {
      name: "separator",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/separator.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/separator.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toolbar": {
      name: "toolbar",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/toolbar.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/toolbar.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "alert-dialog": {
      name: "alert-dialog",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/alert-dialog.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/alert-dialog.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "checkbox-group": {
      name: "checkbox-group",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/checkbox-group.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/checkbox-group.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "preview-card": {
      name: "preview-card",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/preview-card.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/preview-card.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "progress": {
      name: "progress",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/progress.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/progress.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "radio-group": {
      name: "radio-group",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/radio-group.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/radio-group.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "collapsible": {
      name: "collapsible",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/collapsible.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/collapsible.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "scroll-area": {
      name: "scroll-area",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/scroll-area.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/scroll-area.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "slider": {
      name: "slider",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/slider.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/slider.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "label": {
      name: "label",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/label.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/label.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "switch": {
      name: "switch",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/switch.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/switch.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toggle-group": {
      name: "toggle-group",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/toggle-group.tsx",
        type: "registry:ui",
        target: ""
      },{
        path: "registry/default/ui/toggle.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/toggle-group.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "card": {
      name: "card",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/card.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/card.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "badge": {
      name: "badge",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/badge.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/badge.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "skeleton": {
      name: "skeleton",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/skeleton.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/skeleton.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "meter": {
      name: "meter",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/meter.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/meter.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toast": {
      name: "toast",
      description: "",
      type: "registry:ui",
      registryDependencies: ["https://clippkit.com/r/button"],
      files: [{
        path: "registry/default/ui/toast.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/toast.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "textarea": {
      name: "textarea",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/textarea.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/textarea.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "sliding-text-demo": {
      name: "sliding-text-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/sliding-text-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/sliding-text-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "popping-text-demo": {
      name: "popping-text-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/popping-text-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/popping-text-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "popping-text": {
      name: "popping-text",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/popping-text.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/popping-text.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
  },
}
