// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "button": {
      name: "button",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/button.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/button.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "dialog": {
      name: "dialog",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/dialog.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/dialog.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "input": {
      name: "input",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/input.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/input.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "kbd": {
      name: "kbd",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/kbd.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/kbd.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "number-input": {
      name: "number-input",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/number-input.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/number-input.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "dropdown-menu": {
      name: "dropdown-menu",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/dropdown-menu.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/dropdown-menu.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "accordion": {
      name: "accordion",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/accordion.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/accordion.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "checkbox": {
      name: "checkbox",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/checkbox.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/checkbox.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "tabs": {
      name: "tabs",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/tabs.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/tabs.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "avatar": {
      name: "avatar",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/avatar.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/avatar.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "tooltip": {
      name: "tooltip",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/tooltip.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/tooltip.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "select": {
      name: "select",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/select.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/select.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "toggle": {
      name: "toggle",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/toggle.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/toggle.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "popover": {
      name: "popover",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/popover.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/popover.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "separator": {
      name: "separator",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/separator.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/separator.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "toolbar": {
      name: "toolbar",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/toolbar.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/toolbar.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "alert-dialog": {
      name: "alert-dialog",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/alert-dialog.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/alert-dialog.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "checkbox-group": {
      name: "checkbox-group",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/checkbox-group.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/checkbox-group.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "preview-card": {
      name: "preview-card",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/preview-card.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/preview-card.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "progress": {
      name: "progress",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/progress.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/progress.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "radio-group": {
      name: "radio-group",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/radio-group.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/radio-group.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "collapsible": {
      name: "collapsible",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/collapsible.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/collapsible.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "scroll-area": {
      name: "scroll-area",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/scroll-area.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/scroll-area.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "slider": {
      name: "slider",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/slider.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/slider.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "label": {
      name: "label",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/label.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/label.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "switch": {
      name: "switch",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/switch.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/switch.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "toggle-group": {
      name: "toggle-group",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/toggle-group.tsx",
        type: "registry:ui",
        target: ""
      },{
        path: "registry/default/ui/toggle.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/toggle-group.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "card": {
      name: "card",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/card.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/card.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "badge": {
      name: "badge",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/badge.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/badge.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "skeleton": {
      name: "skeleton",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/skeleton.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/skeleton.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "meter": {
      name: "meter",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/meter.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/meter.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "toast": {
      name: "toast",
      description: "",
      type: "registry:ui",
      registryDependencies: ["https://clippkit.com/r/button"],
      files: [{
        path: "registry/default/ui/toast.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/toast.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "textarea": {
      name: "textarea",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/textarea.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/textarea.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "sliding-text-demo": {
      name: "sliding-text-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/sliding-text-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/sliding-text-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "popping-text-demo": {
      name: "popping-text-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/popping-text-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/popping-text-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "glitch-text-demo": {
      name: "glitch-text-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/glitch-text-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/glitch-text-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "typing-text-demo": {
      name: "typing-text-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/typing-text-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/typing-text-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "card-flip-demo": {
      name: "card-flip-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/card-flip-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/card-flip-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "floating-card-demo": {
      name: "floating-card-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/floating-card-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/floating-card-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "toast-card-demo": {
      name: "toast-card-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/toast-card-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/toast-card-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "linear-waveform-demo": {
      name: "linear-waveform-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/linear-waveform-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/linear-waveform-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "bar-waveform-demo": {
      name: "bar-waveform-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/bar-waveform-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/bar-waveform-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "bar-loader-demo": {
      name: "bar-loader-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/bar-loader-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/bar-loader-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "circular-loader-demo": {
      name: "circular-loader-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/circular-loader-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/circular-loader-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "circular-waveform-demo": {
      name: "circular-waveform-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/circular-waveform-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/circular-waveform-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "screen-loader-demo": {
      name: "screen-loader-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/screen-loader-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/screen-loader-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "bar-waveform": {
      name: "bar-waveform",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/bar-waveform.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/bar-waveform.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "circular-waveform": {
      name: "circular-waveform",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/circular-waveform.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/circular-waveform.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "linear-waveform": {
      name: "linear-waveform",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/linear-waveform.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/linear-waveform.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "card-flip": {
      name: "card-flip",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/card-flip.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/card-flip.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "floating-card": {
      name: "floating-card",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/floating-card.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/floating-card.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "toast-card": {
      name: "toast-card",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/toast-card.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/toast-card.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "bar-loader": {
      name: "bar-loader",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/bar-loader.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/bar-loader.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "circular-loader": {
      name: "circular-loader",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/circular-loader.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/circular-loader.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "screen-loader": {
      name: "screen-loader",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/screen-loader.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/screen-loader.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "glitch-text": {
      name: "glitch-text",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/glitch-text.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/glitch-text.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "popping-text": {
      name: "popping-text",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/popping-text.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/popping-text.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "sliding-text": {
      name: "sliding-text",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/sliding-text.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/sliding-text.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "typing-text": {
      name: "typing-text",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/typing-text.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/typing-text.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "u-bar-waveform": {
      name: "u-bar-waveform",
      description: "",
      type: "registry:block",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/blocks/bar-waveform/page.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/components/bar-waveform.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/blocks/bar-waveform/page.tsx")),
      source: "__registry__/default/blocks/bar-waveform/page.tsx",
      category: "",
      subcategory: "",
      meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-6 py-12 items-center md:pt-20 justify-center min-w-0 xl:py-24","mobile":"component"},
      chunks: []
    },
    "u-circular-waveform": {
      name: "u-circular-waveform",
      description: "",
      type: "registry:block",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/blocks/circular-waveform/page.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/components/circular-waveform.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/blocks/circular-waveform/page.tsx")),
      source: "__registry__/default/blocks/circular-waveform/page.tsx",
      category: "",
      subcategory: "",
      meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-6 py-12 items-center md:pt-20 justify-center min-w-0 xl:py-24","mobile":"component"},
      chunks: []
    },
    "u-linear-waveform": {
      name: "u-linear-waveform",
      description: "",
      type: "registry:block",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/blocks/linear-waveform/page.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/components/linear-waveform.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/blocks/linear-waveform/page.tsx")),
      source: "__registry__/default/blocks/linear-waveform/page.tsx",
      category: "",
      subcategory: "",
      meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-6 py-12 items-center md:pt-20 justify-center min-w-0 xl:py-24","mobile":"component"},
      chunks: []
    },
    "u-card-flip": {
      name: "u-card-flip",
      description: "",
      type: "registry:block",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/blocks/card-flip/page.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/components/card-flip.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/blocks/card-flip/page.tsx")),
      source: "__registry__/default/blocks/card-flip/page.tsx",
      category: "",
      subcategory: "",
      meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-6 py-12 items-center md:pt-20 justify-center min-w-0 xl:py-24","mobile":"component"},
      chunks: []
    },
    "u-floating-card": {
      name: "u-floating-card",
      description: "",
      type: "registry:block",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/blocks/floating-card/page.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/components/floating-card.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/blocks/floating-card/page.tsx")),
      source: "__registry__/default/blocks/floating-card/page.tsx",
      category: "",
      subcategory: "",
      meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-6 py-12 items-center md:pt-20 justify-center min-w-0 xl:py-24","mobile":"component"},
      chunks: []
    },
    "u-toast-card": {
      name: "u-toast-card",
      description: "",
      type: "registry:block",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/blocks/toast-card/page.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/components/toast-card.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/blocks/toast-card/page.tsx")),
      source: "__registry__/default/blocks/toast-card/page.tsx",
      category: "",
      subcategory: "",
      meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-6 py-12 items-center md:pt-20 justify-center min-w-0 xl:py-24","mobile":"component"},
      chunks: []
    },
    "u-bar-loader": {
      name: "u-bar-loader",
      description: "",
      type: "registry:block",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/blocks/bar-loader/page.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/components/bar-loader.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/blocks/bar-loader/page.tsx")),
      source: "__registry__/default/blocks/bar-loader/page.tsx",
      category: "",
      subcategory: "",
      meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-6 py-12 items-center md:pt-20 justify-center min-w-0 xl:py-24","mobile":"component"},
      chunks: []
    },
    "u-circular-loader": {
      name: "u-circular-loader",
      description: "",
      type: "registry:block",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/blocks/circular-loader/page.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/components/circular-loader.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/blocks/circular-loader/page.tsx")),
      source: "__registry__/default/blocks/circular-loader/page.tsx",
      category: "",
      subcategory: "",
      meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-6 py-12 items-center md:pt-20 justify-center min-w-0 xl:py-24","mobile":"component"},
      chunks: []
    },
    "u-screen-loader": {
      name: "u-screen-loader",
      description: "",
      type: "registry:block",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/blocks/screen-loader/page.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/components/screen-loader.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/blocks/screen-loader/page.tsx")),
      source: "__registry__/default/blocks/screen-loader/page.tsx",
      category: "",
      subcategory: "",
      meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-6 py-12 items-center md:pt-20 justify-center min-w-0 xl:py-24","mobile":"component"},
      chunks: []
    },
    "u-glitch-text": {
      name: "u-glitch-text",
      description: "",
      type: "registry:block",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/blocks/glitch-text/page.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/components/glitch-text.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/blocks/glitch-text/page.tsx")),
      source: "__registry__/default/blocks/glitch-text/page.tsx",
      category: "",
      subcategory: "",
      meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-6 py-12 items-center md:pt-20 justify-center min-w-0 xl:py-24","mobile":"component"},
      chunks: []
    },
    "u-popping-text": {
      name: "u-popping-text",
      description: "",
      type: "registry:block",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/blocks/popping-text/page.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/components/popping-text.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/blocks/popping-text/page.tsx")),
      source: "__registry__/default/blocks/popping-text/page.tsx",
      category: "",
      subcategory: "",
      meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-6 py-12 items-center md:pt-20 justify-center min-w-0 xl:py-24","mobile":"component"},
      chunks: []
    },
    "u-sliding-text": {
      name: "u-sliding-text",
      description: "",
      type: "registry:block",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/blocks/sliding-text/page.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/components/sliding-text.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/blocks/sliding-text/page.tsx")),
      source: "__registry__/default/blocks/sliding-text/page.tsx",
      category: "",
      subcategory: "",
      meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-6 py-12 items-center md:pt-20 justify-center min-w-0 xl:py-24","mobile":"component"},
      chunks: []
    },
    "u-typing-text": {
      name: "u-typing-text",
      description: "",
      type: "registry:block",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/blocks/typing-text/page.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/components/typing-text.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/blocks/typing-text/page.tsx")),
      source: "__registry__/default/blocks/typing-text/page.tsx",
      category: "",
      subcategory: "",
      meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-6 py-12 items-center md:pt-20 justify-center min-w-0 xl:py-24","mobile":"component"},
      chunks: []
    },
    "u-bar-waveform-page": {
      name: "u-bar-waveform-page",
      description: "",
      type: "registry:page",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/blocks/bar-waveform/page.tsx",
        type: "registry:page",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/blocks/bar-waveform/page.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
  },
}
